# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SignIn' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'

  target 'SignInTests' do
    inherit! :search_paths
    pod 'RxTest'
    pod 'RxBlocking'
  end
end
